id: productPromo
name: Product Promo
icon: shopping-cart
parameters:
  - id: product
    name: Product
    type: medusa-product-selector
    helpText: ''
    typeConfig:
      allowedCollections:
        pcol_01GMNH7YD3EANAXKVRHB7KK63E:
          id: pcol_01GMNH7YD3EANAXKVRHB7KK63E
          name: Monitors
        pcol_01GMNH87C30FH24K6PMQZPQE0Q:
          id: pcol_01GMNH87C30FH24K6PMQZPQE0Q
          name: Laptops
useTeamPermissions: true
slots: []
canBeComposition: false
created: '2023-01-08T23:08:47.79779+00:00'
updated: '2023-01-08T23:08:54.480047+00:00'
